In [1]:
import os

In [2]:
os.listdir()

['diabetes.csv', '.ipynb_checkpoints', 'Untitled.ipynb']

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('diabetes.csv')

In [60]:
df.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [9]:
X = df.iloc[:,1:5]

In [10]:
X

     Glucose  BloodPressure  SkinThickness  Insulin
0        148             72             35        0
1         85             66             29        0
2        183             64              0        0
3         89             66             23       94
4        137             40             35      168
..       ...            ...            ...      ...
763      101             76             48      180
764      122             70             27        0
765      121             72             23      112
766      126             60              0        0
767       93             70             31        0

[768 rows x 4 columns]

In [17]:
y = df.iloc[:,8:]

In [18]:
y

     Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [38]:
X_train

     Glucose  BloodPressure  SkinThickness  Insulin
253       86             68             32        0
660      162             84              0        0
7        115              0              0        0
313      113             50             10       85
575      119             44             47       63
..       ...            ...            ...      ...
235      171             72              0        0
117       78             48              0        0
474      114             64              0        0
532       86             66             52       65
446      100             72             12       70

[537 rows x 4 columns]

In [39]:
y_train

     Outcome
253        0
660        0
7          0
313        0
575        0
..       ...
235        1
117        0
474        0
532        0
446        0

[537 rows x 1 columns]

In [40]:
regressor = LinearRegression()

In [41]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
prediction = regressor.predict(X_test)

In [43]:
mean_squared_error(y_test,prediction)

0.17569585634393017

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
logi = LogisticRegression()
logi.fit(X_train,y_train)

/home/sunbeam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [46]:
y_pred = logi.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score

In [48]:
accuracy_score(y_test,y_pred)

0.7316017316017316

In [50]:
from pycaret.datasets import get_data
diabetes = get_data('diabetes')

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [51]:
from pycaret.classification import *
exp1 = setup(diabetes,target = 'Class variable')

Setup Succesfully Completed!

In [52]:
compare_models()

In [53]:
from sklearn.linear_model import RidgeClassifier

In [54]:
ridge = RidgeClassifier()

In [55]:
ridge.fit(X_train,y_train)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=None,
                solver='auto', tol=0.001)

In [57]:
y_pred1 = ridge.predict(X_test)

In [58]:
accuracy_score(y_test,y_pred1)

0.7402597402597403

####